"""Build ../supplement.tex: the preamble (packages and the macro definitions that generate the numbers) is taken from ../main.tex, so that the two documents cannot drift apart, followed by
the tables of ../supplement_body.tex at full size on landscape pages.
   python scripts/make_supplement.py           # then, from the project root: tectonic --keep-logs supplement.tex
main.tex refers to the tables by key (supp_numbers.tex); the supplement checks the numbering while it is compiled."""
import re
import sys

MAIN, BODY, OUT = "../main.tex", "../supplement_body.tex", "../supplement.tex"

HEAD = r"""% Generated by lychee-code/scripts/make_supplement.py from main.tex (preamble) and supplement_body.tex (tables). Edit those, not this file.
\documentclass[11pt,a4paper]{article}
\usepackage[margin=0.9in,landscape]{geometry}
\usepackage{amsmath,amssymb,amsthm,bm}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{array}
\usepackage{url}
\usepackage[hidelinks]{hyperref}
\usepackage{xcolor}
\usepackage{microtype}
\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\topfraction}{0.9}\renewcommand{\textfraction}{0.05}\renewcommand{\floatpagefraction}{0.7}\setcounter{topnumber}{3}
"""

INTRO = r"""
\title{Supplementary material to ``Which Lychee? A Counterfactual Benchmark and Controlled Study of Command-Conditioned Target Selection in Simulated Harvesting''}
\author{}\date{}
\begin{document}
\maketitle
\noindent This supplement holds the tables of the main paper that are not needed to follow its argument, at full size. Every number in them is generated by the scripts of the code
repository from the per-command result files (Data Availability statement of the main paper); none was typed by hand. Tables~S1--S3 give the selection track of seed~0, the PTA by command
family on IID scenes and on the occlusion split; Tables~S4--S6 give the exploratory comparisons of the selection track (the planned comparisons are in the main paper). The comparisons
are exploratory: their intervals are not corrected for multiplicity, and no design constant was set from them.

"""


def main():
    main_tex = open(MAIN, encoding="utf-8").read()
    i, j = main_tex.index("\\newcommand{\\bench}"), main_tex.index("\\title{")
    block = main_tex[i:j]
    block = block.replace("\\input{supp_numbers.tex}   % numbers of the tables of the separate supplement (supplement.tex checks them)\n", "")
    body = open(BODY, encoding="utf-8").read().replace("\\begin{table}[h]", "\\begin{table}[htbp]")
    out = HEAD + block.rstrip("\n") + "\n\\input{supp_numbers.tex}\n" + INTRO + body + "\n\\end{document}\n"
    open(OUT, "w", encoding="utf-8", newline="\n").write(out)
    print(f"{OUT}: {out.count(chr(10))} lines, {len(re.findall(r'begin.table.', out))} tables")


if __name__ == "__main__":
    sys.exit(main())
